### ISSUE TITLE
RCs of packages fail to deploy

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/javascript#292]
## Explanation

We encountered a problem when making RCs of the javascript packages: after running `yarn lerna-version-rc` this was the build on Travis: https://travis-ci.com/Yoast/javascript/builds/112741344

We noticed that there was no `rc-deployment` step as you usually get with `Publish` builds, see e.g. this previous build: https://travis-ci.com/Yoast/javascript/builds/111883290

This means that the new RCs weren’t deployed (also confirmed by checking on NPM).

The only thing done differently than usual is that we deployed from a feature branch instead of a release branch. (Is there any difference that can arise just from the naming of branches?)

**Comment by andizer** [comment]
I think there is a restriction in branchenames. For a RC it should contain (or start with) `release-yoast-seo` or `release`.

This is what I see in the `travis.yml` file:
```
stages:
  - test
  - name: 🚀 rc-deployment
    if: branch =~ /^(release-yoast-seo|release)\/*/
  - name: 🚀 deployment
    if: branch = master
```
